# Generated by Django 2.2.10 on 2020-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('state_id', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=255)),
                ('country_id', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('longitude', models.CharField(max_length=255)),
            ],
        ),
    ]
