# Generated by Django 2.2.10 on 2020-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('iso3', models.CharField(max_length=255)),
                ('iso2', models.CharField(max_length=255)),
                ('phone_code', models.CharField(max_length=255)),
                ('capital', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('native', models.CharField(max_length=255)),
                ('emoji', models.CharField(max_length=255)),
                ('emojiU', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country_id', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('state_code', models.CharField(max_length=255)),
            ],
        ),
    ]
